---
title: "Disciplina: Projetos de análise de dados usando R"
subtitle: "Dia 1: Introdução à Ciência Aberta"
author: "Andrea Sánchez Tapia, Sara Mortara, Diogo Rocha"
date: "2019/06/17 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: middle

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```



---
class: middle, inverse, center


# O que é ciência aberta e por que pensar nela num curso sobre análise de dados em R?

---
# O que é ciência aberta?

+ Um movimento que busca que todos os produtos da pesquisa científica sejam disponíveis publicamente

+ Dados e conteúdo aberto poderiam ser __usados__, __modificados__, __compartilhados__ livremente por qualquer pessoa, para qualquer propósito

+ O conhecimento é aberto se qualquer pessoa está livre para acessá-lo, utilizá-lo, modificá-lo, e compartilhá‑lo — restrito, no máximo, a medidas que preservam a proveniência e abertura.

+ __Desde os dados originais até a publicação final, incluindo a metodologia.__

---
# Os seis pilares da ciência aberta

1. __Dados__ abertos para disponibilizar os grupos de dados sem tratamento
--

1. __Ferramentas__ "open source" - não apenas gratuitas, mas de código aberto.
--

1. __Metolodogia aberta__, compartilhando os detalhes e as ferramentas para garantir transparência e reprodutibilidade
--

1. __Acesso__ aberto para a publicação dos resultados
--

1. __Revisão__ (_peer review_) aberta
--

1. __Fontes de educação__ abertas

--

.footnote[
+ Kraker, P., Leony, D., Reinhardt, W., & Beham, G. (2011). The Case for an Open Science in Technology Enhanced Learning. International Journal of Technology Enhanced Learning, 6(3), 643–654  
+ http://opendefinition.org/od/2.1/en/  
+ https://nikokriegeskorte.org/2016/02/15/the-four-pillars-of-open-science/

]

---
# Passos para que nossa pesquisa seja (mais) aberta

1. Refletir sobre a questão ética subjacente, entender por que é importante.
Recursos públicos, extensão, impacto, alfabetização científica, valorização da ciência. Robusteza nos resultados, resolver a crise de reprodutibilidade. 
1. Entender o contexto legal
 + Saber quando _não_ se devem compartilhar os dados
 (sujeitos humanos, registros de espécies comercializadas)
 + Distinguir entre publicações abertas e predatórias
 + Entender as restrições que persistem apesar de a pesquisa ser aberta
1. Examinar as práticas diárias de pesquisa
 + Que fases de meu trabalho poderiam ser mais abertas? (dados, publicações, metodologias...)
 + Quais são as limitações que devo considerar ou superar hoje?
1. Quais ferramentas e comunidades existem para que ajudar a fazer ciência (mais) aberta

.footnote[
(modificado de Marcela Alfaro - Universidade da Costa Rica)
]
---
# Barreiras para o progresso em direção a uma ciência aberta

The major barriers to progress are not technological, but psychological, cultural, and political: individual habits, institutional inertia, unhealthy incentives, and vested interests. The biggest challenge is the fact that the present way of doing science does work (albeit suboptimally) and our vision for open science has not merely not yet been implemented, but has yet to be fully conceived. We will need to find ways to gradually evolve our individual workflows and our scientific culture.(https://nikokriegeskorte.org/2016/02/15/the-four-pillars-of-open-science/)

__Malpractice__ pode ser uma grande barreira para o compartilhamento de dados, metodologias - ela deve ser corrigida.


---
# Ferramentas e fluxos de trabalho

https://101innovations.wordpress.com/workflows/

+ Onde você procura artigos?
 + Tabelas de conteúdo, feeds RSS, Google Scholar, listas de email, twitter, F1000, ResearchGate
--

+ Como você toma os dados?
 + Lápis, papel
 + Spreadsheets (Excel, LibreOffice). 
 + Bases de dados estruturadas? 
 + Bases de dados do laboratório?
--

+ Onde você guarda seus dados? 
 + Dropbox, github, repositórios, backup institucional.
 + Os __formatos__ são abertos? O software é proprietário? .csv vs. .xls, por exemplo. Daqui a 5, 10, 100 anos poderemos ver os dados?
 
--

Um formato aberto não impõe restrições monetárias ou de qualquer tipo sobre seu uso e pode ser processado completamente em pelo menos uma ferramenta de software libre/gratuita/open-source. (http://opendefinition.org/od/2.1/en)

---

+ Como você analisa seus dados?
__`R`__

--

+ Como você escreve sua dissertação? seus manuscritos? Microsoft Word, né? Você comprou o Microsoft Word?

--

+ Onde você publica? Revistas de acesso aberto? 
--

+ Como você divulga sua pesquisa? researchgate, twitter

--

+ Como sua pesquisa é avaliada? Índices de impacto (a revista), índices H (você), __altmetrics__, engajamento digital (twitter por ex.)

---
class: middle, inverse, center

# A Reprodutibilidade é o eixo da análise de dados aberta

https://www.nature.com/news/1-500-scientists-lift-the-lid-on-reproducibility-1.19970

---

---
# Mais referências
+ Open Science Framework https://osf.io/
+ Blog OpenScience.com https://openscience.com/
+ Gorgolewski, Krzysztof J., y Russell A. Poldrack. “A Practical Guide for Improving Transparency and Reproducibility in Neuroimaging Research”. BioRxiv, febrero de 2016, p. 039354. www.biorxiv.org, doi:10.1101/039354.
+ NIH - Instruction in Responsible Conduct of Research https://oir.nih.gov/sourcebook/ethical-conduct/responsible-conduct-research-training/
+ Zook, Matthew, et al. “Ten Simple Rules for Responsible Big Data Research”. PLOS Computational Biology, vol. 13, núm. 3, marzo de 2017, p. e1005399. PLoS Journals, doi:10.1371/journal.pcbi.1005399.

---
class: middle
# O que é ciência responsável?

A gente escreve projetos, desenha experimentos, toma dados, analisa, dicsute, escreve, submete, publica
Revisa, lida com recursos públicos, orienta, colabora

__A análise de dados é apenas uma parte__

---
# Responsible Conduct of Research (NIH, NSF)

1. Integridade científica
1. Aqcuisição, manejo, compartilhamento, autoria de dados
__Como os dados da pesquisa, como cadernos de laboratório (notas de campo) deveriam ser mantidos? Quem é dono e quem tem acesso?__
1. Práticas de publicação e autoria responsável
1. Revisão por pares
1. Relação orientador-orientado
1. Ciência colaborativa
1. Pesquisa em sujeitos humanos e animais
1. Conflitos de interesse e Responsabilidade

Treinamento online  Introduction to the Responsible Conduct of Research. https://researchethics.od.nih.gov/

---

# Análise de dados e integridade da pesquisa: 

+ Usar programas para gerar gráficos que melhorem os dados de uma maneira que modifique os resultados
 
+ Modificar o método de análise para obter os resultados desejados
 
+ Omitir dados que não suportam suas conclusões
 
+ Fabricar dados e reportar dados falsos como reais
 
+ Modificar deliberadamente os dados
 
+ Reportar os mesmos dados em publicações múltiples (_"salami science"_)

---

# Ciência de dados responsável (Responsible data science)
https://redasci.org/

+ Data science without prejudice – How to avoid unfair conclusions even if they are true?
+ Data science without guesswork – How to answer questions with a guaranteed level of  accuracy?
+ Data science that ensures confidentiality – How to answer questions without revealing secrets?
+ Data science that provides transparency – How to clarify answers such that they become indisputable?


---
# Aquisição e manejo/manutenção de dados científicos

+ __Protocolos experimentais__: o plano detalhado de um experimento, tratamento ou proedimento científico ou médico.

+ __Dados primários__:
  + Calibração dos instrumentos e seu _output_
  + Dados brutos
  + Dados processados
  + Cálculos estatísticos
  + Gravações análogas e digitais
  + Imagens fotográficas e de microscopia
  + Arquivos eletrônicos

+ __Procedimentos de redução (limpeza) e análise__.

.footnote[
https://researchethics.od.nih.gov/DataManagement2.aspx
]

---
# O que deve ser registrado?

+ Os métodos e sua lógica, detalhes sobre o processamento dos dados brutos
+ Materiais utiilizados, localização da coleta
+ Os dados e observações
+ Passos próximos
+ Marcação adequada das amostras e identificação de todos os dados

__METADADOS__

O caderno de laboratório/de campo é um registro permanente, bem organizado, compreensível, completo, que permita a replicação por outros.

---
# Quem é responsável?
Qualquer indivíduo envolvido no desenvolvimento e execução da pesquisa e procesamento dos dados

+ Os estudantes
+ O pesquisador principal
+ O orientador
+ Os assistentes de laboratório
+ Os assistentes de campo etc. 


# Manutenção e compartilhamento

+ Longo prazo - reanálise
+ Repetição, replicação


---
# Metodologia aberta

Cada publicação deve conter toda a informação necessária para que outros cientistas possam repetir o trabalho e a lista completa de referênciasusadas para realizar a pesquisa.

Facilita a colaboração
